#!/usr/bin/env ruby

# USAGE: dbbackup <environment> [/full/path/to/mysqldump]

require 'yaml'

RAILS_ROOT  = File.dirname(__FILE__) + '/../'
RAILS_ENV = ARGV[0]
MYSQLDUMP_PATH = (ARGV[1].nil? ? `which mysqldump`.chomp : ARGV[1])
DUMP_FILE = "#{RAILS_ROOT}/db/dump_#{RAILS_ENV}.sql.gz"
settings = YAML::load_file("#{RAILS_ROOT}/config/database.yml")[RAILS_ENV]

abort "USAGE: dbbackup <environment> [/full/path/to/mysqldump]" if settings.nil?

abort "Can't find mysqldump. Run with as 'dbbackup #{RAILS_ENV} </full/path/to/mysqldump> '" unless File.exists?(MYSQLDUMP_PATH)

`#{MYSQLDUMP_PATH} -u #{settings['username']} --password=#{settings['password']} #{settings['database']} | gzip > #{DUMP_FILE}`

abort "Failed to write '#{DUMP_FILE}' (bad mysqldump path?)" if File.size?(DUMP_FILE).nil? or (File.mtime(DUMP_FILE) - Time.now) > 60

`svn add #{DUMP_FILE}` if `svn st #{DUMP_FILE}`[0].chr == '?'
`svn commit #{DUMP_FILE} -m '#{RAILS_ENV} database dump'`